version: 3.1.0

pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: /wespeaker-voxceleb-resnet34-LM/pytorch_model.bin     # 提取embedding的网络模型路径
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: /segmentation-3.0/pytorch_model.bin # 提取segmentation的网络模型路径
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0
